#!/usr/bin/env bash

selected=$(
    ~/.local/scripts/listSessions.sh | fzf --multi \
        --prompt "Select a TMUX session or directory: " \
        --bind 'ctrl-x:execute(tmux kill-session -t {})+reload(~/.local/scripts/listSessions.sh)'
)
if [[ -z $selected ]]; then
    echo "No directory selected."
    exit 0
fi

selected_name=$(basename "$selected" | tr . _ | sed 's/\[TMUX\]\///')

if [[ -z $TMUX ]]; then
    tmux new-session -A -s "$selected_name" -c "$selected"
    exit 0
fi

# Check if the session already exists

if ! tmux has-session -t "$selected_name" 2>/dev/null; then
    echo "Creating new session: $selected_name"
    tmux new-session -ds "$selected_name" -c "$selected"
fi
tmux switch-client -t "$selected_name"
