-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
-- vim.keymap.set("n", "<leader>ccb", ":CMakeBuild<CR>", { desc = "CMake Build" })
-- vim.keymap.set("n", "<leader>cct", ":CMakeSelectBuildType<CR>", { desc = "CMake Build Type" })
-- vim.keymap.set("n", "<leader>ccc", ":CMakeRun<CR>", { desc = "CMake Run" })
-- vim.keymap.set("n", "<leader>cce", ":CMakeDebug<CR>", { desc = "CMake Debug" })
-- Put this in your init.lua or a plugin/lua file
